### PR TITLE
Update version of velocity

### PR DESCRIPTION
**Pull request by kpeatt**
Status: **Donut Merge**
Reviewers: @scalvert @tedtate 
## Changes
- Update to latest version of Velocity

### CODE REVIEW

**Comment by highruned** [comment]
Looks legit to me

**Comment by kpeatt** [comment]
Fuck yeah it does.

**Comment by highruned** [comment]
:laughing:

**Comment by tedtate** [comment]
This guy. Leavin' his donut merges out in the sun.

**Comment by donnielrt** [comment]
Hey, we’re looking to prune older abandoned PRs. If this PR is still relevant and you would like to see it merged in, please reopen the PR and we’ll add it to our backlog! Thanks!

**Pull request closed without merging**
